  ActiveAdminPanel[m
  Adding_API[m
  Adding_Doorkeeper[m
* [32mAdding_Factorygirl[m
  Adding_Rspec[m
  Created_custom_API[m
  Date_and_password_validation[m
  addedlogtouser[m
  addingValidationRoom[m
  hotelsearchfeature[m
  main[m
  userviews[m
  [31mremotes/origin/ActiveAdminPanel[m
  [31mremotes/origin/Adding_API[m
  [31mremotes/origin/Adding_Doorkeeper[m
  [31mremotes/origin/Adding_Rspec[m
  [31mremotes/origin/Created_custom_API[m
  [31mremotes/origin/Date_and_password_validation[m
  [31mremotes/origin/addedlogtouser[m
  [31mremotes/origin/addingValidationRoom[m
  [31mremotes/origin/hotelsearchfeature[m
  [31mremotes/origin/main[m
  [31mremotes/origin/userviews[m
